apiVersion: rbac-manager.k8smgmt.io/v1
kind: RBACPolicy
metadata:
  labels:
    app.kubernetes.io/name: rbacpolicy
    app.kubernetes.io/instance: tc005-custom-role
    app.kubernetes.io/part-of: rbac-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rbac-manager
  name: tc005-custom-role
spec:
  version: 1.0.0
  namespaceCreatePolicy: "IfNotPresent" # (or) "Never"
  customRoles:
    - name: edit
      namespace: default
      denyResources:
        - services
        - secrets
      allowedVerbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
      allowedGroups:
        - ""
        - admissionregistration.k8s.io
        - storage.k8s.io
        - networking.k8s.io
