apiVersion: rbac-manager.k8smgmt.io/v1
kind: RBACPolicy
metadata:
  labels:
    app.kubernetes.io/name: rbacpolicy
    app.kubernetes.io/instance: rbacpolicy-sample
    app.kubernetes.io/part-of: rbac-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rbac-manager
  name: tc001-native-clusterrole
spec:
  version: 1.0.0
  namespaceCreatePolicy: "IfNotPresent" # (or) "Never"
  clusterRoles:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      rules:
      - apiGroups: [""] # "" indicates the core API group
        resources: ["secrets"]
        verbs: ["get", "watch", "list"]
      metadata:
        name: cr-secret-reader
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: cr-secret-write
      rules:
      - apiGroups: [""] # "" indicates the core API group
        resources: ["secrets"]
        verbs: [ "get", "watch", "list", create, update, patch, delete]