apiVersion: rbac-manager.k8smgmt.io/v1
kind: RBACPolicy
metadata:
  labels:
    app.kubernetes.io/name: rbacpolicy
    app.kubernetes.io/instance: tc006-custom-role
    app.kubernetes.io/part-of: rbac-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rbac-manager
  name: tc006-custom-role
spec:
  version: 1.0.0
  namespaceCreatePolicy: "IfNotPresent" # (or) "Never"
  customRoles:
    - name: edit
      namespaceSelector:
        matchLabels:
          key1: value1
        matchExpressions:
          - {key: name, operator: In, values: [payroll, web]}
          - {key: environment, operator: NotIn, values: [dev]}
      shared: false
      denyResources:
        - services
        - secrets
      allowedVerbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
      allowedGroups:
        - ""
        - admissionregistration.k8s.io
        - storage.k8s.io
        - networking.k8s.io
